version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: gandlaf-openpleb_server_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
  server:
    image: gandlaf21/openpleb-umbrel-app:0.0.1@sha256:393266667474545913a0b0fc23cf0d9123f9d566aeb4446f9ab1c598cd9d6476
    restart: on-failure
    stop_grace_period: 5s
    environment:
      - CONFIG_PATH=/data/config
    volumes: 
      - ${APP_DATA_DIR}/data:/data
    ports:
      - "7777:3000"

  backend:
    image: gandlaf21/openpleb-backend:0.1.0@sha256:f12ad50ef107b483d34a7c1d4ad074ad5883139f2d97f013fc087d824cb6c769
    restart: unless-stopped
    env_file: 
     - ${APP_DATA_DIR}/data/config/backend/.env
    ports:
      - "3044:3003"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    depends_on:
      - postgres

  frontend:
    image: gandlaf21/openpleb-frontend:0.0.1@sha256:a77fd31a86c27357155a38859814a5c327ad7f39a8123b88f9d5036ad1e73a2a
    restart: unless-stopped
    env_file:
     - ${APP_DATA_DIR}/data/config/frontend/.env
    ports:
      - "3010:3000"
    depends_on:
      - backend
    volumes:
      - ${APP_DATA_DIR}/data/config/frontend/.env:/app/data/config/frontend/.env

  admin-frontend:
    image: gandlaf21/openpleb-admin-frontend:0.0.1@sha256:3f419e1d3a9afe41f44c38fb00b8305473ba413de43b25525882c3f629acfe17
    restart: unless-stopped
    env_file: 
     - ${APP_DATA_DIR}/data/config/frontend/.env
    ports:
      - "3011:3000"
    depends_on:
      - backend
    volumes:
      - ${APP_DATA_DIR}/data/config/admin-frontend/.env:/app/data/config/admin-frontend/.env
      
  postgres:
    image: postgres:15.3-alpine3.18@sha256:4ca65a9209f164bdb30f715ac2ed9182cc0737d0f0a549031b3c1b0b7e652f3a
    restart: unless-stopped
    env_file: 
     - ${APP_DATA_DIR}/data/config/db/.env
    ports:
      - "5439:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ${APP_DATA_DIR}/data/config/db/.env:/app/data/config/db/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
    driver: local

