version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: gandlaf-cdk_server_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
    
  server:
    image: gandlaf21/cdk-app:0.0.2@sha256:a3c4715150bdbcf6439e4a3170c7d24cb80a55c775a78d4f6a8f15d857ad89fb
    restart: on-failure
    stop_grace_period: 5s
    ports:
      - "5555:3000"

  mintd:
    image: gandlaf21/cdk:0.9.2@sha256:15d3a8b8336ffd75831f3cb5618c1590d402370f1aa4df2a3bfafea21f0be691
    restart: on-failure
    stop_grace_period: 5s
    ports:
      - "8085:8085"
    command: ["cdk-mintd"]
    environment:
      - CONFIG_PATH=${PWD}/data/.cdk-mintd/config.toml
    volumes: 
      - ${APP_DATA_DIR}/data:/data
      - ${PWD}/data/.cdk-mintd:/root/.cdk-mintd/
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd
