version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: gandlaf-cdk_server_1
      APP_PORT: 6754
    
  server:
    image: gandlaf21/cdk-app:latest
    restart: on-failure
    stop_grace_period: 5s
    ports: 
      - "6754:3000"
    init: true
  mintd:
    image: gandlaf21/cdk:0.9.2
    restart: on-failure
    stop_grace_period: 5s
    ports:
      - "8085:8085"
    environment:
      - CDK_MINTD_URL=https://example.com
      - CDK_MINTD_LN_BACKEND=fakewallet
      - CDK_MINTD_LISTEN_HOST=0.0.0.0
      - CDK_MINTD_LISTEN_PORT=8085
      - CDK_MINTD_MNEMONIC=quarter season champion wagon abuse point doll blossom funny snake radio stamp
      - CDK_MINTD_DATABASE=redb
      - CDK_MINTD_CACHE_BACKEND=memory
      - CDK_MINTD_CACHE_REDIS_URL=redis://redis:6379 
      - CDK_MINTD_CACHE_REDIS_KEY_PREFIX=cdk-mintd
    command: ["cdk-mintd"]
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: mint_redis
    ports:
      - "6379:6379"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command: redis-server --save 60 1 --loglevel warning
